name: jogo_da_memoria
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/images/easy/
  - assets/images/medium/
  - assets/images/head/
  - assets/images/body/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/jogo_da_memoria.png"
